config/routes.rb
Rails.application.routes.draw do
  
 
      resources :users, except:[:new, :show] do
      resources :destinations
      resources :flights, only: [:update, :destroy, :create]
      resources :pilots,  only: [:update, :destroy, :create]
      resources :passengers, only: [:update, :destroy, :create]
      
  

  end

      root to:'static#home'
     
      get '/auth/:provider/callback', :to => 'sessions#github_create'
      
  
 
  
      get '/users/signup', to: 'users#new', as: 'new_user'
      get '/login',  to: 'sessions#new', as: 'login'
      post 'login', to: 'sessions#create'
      get '/users/:id', to: 'users#show'
      delete '/users', to: 'users#destroy'
  
      delete 'session', to: 'sessions#destroy', as: 'logout'

      get '/users/:user_id/destinations', to: "destinations#index", as: 'destinations'
      get '/users/:user_id/destinations/:id', to: "destinations#show", as: 'destination'
  
 
      
      get '/users/:user_id/pilots/search' => 'pilots#search', :as => 'search_pilot'
 
  
  # post '/login'   to: 'sessions#create'
  # post '/signin', to: 'sessions#create'
 
  
  
  
 
  #destinations
  
  #users
  
  
  

  #flights
  get '/users/:user_id/flights', to: 'flights#index', as: 'flights'
  get '/users/:user_id/flights/new', to: 'flights#new', as: 'new_flight'
  get '/users/:user_id/flights/:id', to: 'flights#show', as: 'flight'
  get '/users/:user_id/flights/:id/edit', to: 'flights#edit', as: 'edit_flight'
  get '/users/:user_id/most', to: 'pilots#most', as: 'most_pilot'
  #pilot
  get '/users/:user_id/pilots', to: 'pilots#index', as: 'pilots'
  get '/users/:user_id/pilots/new', to: 'pilots#new', as: 'new_pilot'
  get '/users/:user_id/pilots/:id', to: 'pilots#show', as: 'pilot'
  get '/users/:user_id/pilots/:id/edit', to: 'pilots#edit', as: 'edit_pilot'
  
  
  #passenger
  get '/users/:user_id/pasengers', to: 'passengers#index', as: 'passengers'
  get '/users/:user_id/passengers/new', to: 'passengers#new', as: 'new_passenger'
  get '/users/:user_id/passengers/:id', to: 'passengers#show', as: 'passenger'
  get '/users/:user_id/passengers/:id/edit', to: 'passengers#edit', as: 'edit_passenger'

  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
 
  
    has_many :flights
    has_many :pilots
    has_many :passengers
    has_many :destinations
    has_secure_password
    validates_presence_of :username, :password
    validates :username, uniqueness: true
    validates_length_of :username,  in: 6..10
    validates_length_of :password, in: 6..20 
    validates :username, uniqueness: true
    
    def self.create_with_omniauth(auth)
        create! do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.name = auth["info"][name]
        end
    end
    
    

    

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verified_user, only:[:new, :create]
    layout 'flightlayout'

    def index
        @users = User.all
    end
    
    def new
        @user = User.new
        render 'new'
    end

    def create
        @user = User.create(user_params)       
        if @user.save 
            session[:user_id] = @user.id                                                                                                        
            redirect_to @user
        else
            render 'new'
        end
    end


    def show
        @user = User.find_by(id: params[:id])
    end


    def destroy
        @user = User.find_by(id: params[:id])
        @user.destroy
        redirect_to users_path
    end
   
    
 
    

private

    def user_params
        params.require(:user).permit(:username,:password,:admin)
    end



end

app/views/users/index.html.erb
<div class='container users'>
<h2>Users Of The Application</h2>
<div>
<ul>
Non Admin Users:
<% @users.each do |user| %>
    <% if user.admin %>
    
    <% else%>

    <li><%= user.username %> | <%= link_to 'Delete',user_path(user), method: :delete %></li>
    <% end %>
<% end %>
</ul>
</div>
<hr>
<div>
<ul>
All Users:
<% @users.each do |user| %>
    <% if user.admin != current_user %>
    <li><%= user.username %></li>
    
    <% end %>
<% end %>
</ul>
</div>

<%= link_to 'Back', user_path(current_user) %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div>
  <% if @user.errors.any? %>
   <divt class="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prevented this record from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li style='color:red;'><%= msg %></li>
  <% end %>
  </ul>
  </div>
  <% end %>
</div>

<%= form_for @user do |f|%>
  
  <p>
  <%= f.label :username %>
  <%= f.text_field :username, required: true %>
  </p>
  <p>
  <%= f.label :password %>
  <%= f.password_field :password, required: true %>
  </p>
  <%= f.label(:admin, "Admin") %>
  <%= f.check_box(:admin, id: "user_admin") %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', root_path%>

app/views/users/show.html.erb
<div class= 'container usershow'>
<% flash.each do |type, msg| %>
  <div>
    <h4><li style="color:green;"><%= msg %></li></h4>
  </div>

<% end %>


<div class='content'>
<h2>Welcome to Flight Scheduler</h2>

<% if logged_in %>
    <h2>You are logged in as <%= current_user.username %></h2>
<%end%>

<h3><%= link_to "Create New Flight", new_flight_path(current_user) %></h3>
<h3><%= link_to "Meet your pilots", user_pilots_path(current_user) %></h3>
<h3><%= link_to "See what cities we are currently servicing", destinations_path(current_user)%></h3>
<h3><%= link_to "Current Flight(s)", flights_path(current_user)%></h3>
<h3><%= link_to "Top Pilot", most_pilot_path(current_user) %></h3>
<div>

<%= link_to "Log Out", "/session", method: :delete %> | <% if current_user.admin%> <%= link_to "Admin Use Only" , users_path %> <% end %>
</div>

</div>