config/routes.rb
Rails.application.routes.draw do
  
 
      resources :users, except:[:new, :show] do
      resources :destinations
      resources :flights, only: [:update, :destroy, :create]
      resources :pilots,  only: [:update, :destroy, :create]
      resources :passengers, only: [:update, :destroy, :create]
      
  

  end

      root to:'static#home'
     
      get '/auth/:provider/callback', :to => 'sessions#github_create'
      
  
 
  
      get '/users/signup', to: 'users#new', as: 'new_user'
      get '/login',  to: 'sessions#new', as: 'login'
      post 'login', to: 'sessions#create'
      get '/users/:id', to: 'users#show'
      delete '/users', to: 'users#destroy'
  
      delete 'session', to: 'sessions#destroy', as: 'logout'

      get '/users/:user_id/destinations', to: "destinations#index", as: 'destinations'
      get '/users/:user_id/destinations/:id', to: "destinations#show", as: 'destination'
  
 
      
      get '/users/:user_id/pilots/search' => 'pilots#search', :as => 'search_pilot'
 
  
  # post '/login'   to: 'sessions#create'
  # post '/signin', to: 'sessions#create'
 
  
  
  
 
  #destinations
  
  #users
  
  
  

  #flights
  get '/users/:user_id/flights', to: 'flights#index', as: 'flights'
  get '/users/:user_id/flights/new', to: 'flights#new', as: 'new_flight'
  get '/users/:user_id/flights/:id', to: 'flights#show', as: 'flight'
  get '/users/:user_id/flights/:id/edit', to: 'flights#edit', as: 'edit_flight'
  get '/users/:user_id/most', to: 'pilots#most', as: 'most_pilot'
  #pilot
  get '/users/:user_id/pilots', to: 'pilots#index', as: 'pilots'
  get '/users/:user_id/pilots/new', to: 'pilots#new', as: 'new_pilot'
  get '/users/:user_id/pilots/:id', to: 'pilots#show', as: 'pilot'
  get '/users/:user_id/pilots/:id/edit', to: 'pilots#edit', as: 'edit_pilot'
  
  
  #passenger
  get '/users/:user_id/pasengers', to: 'passengers#index', as: 'passengers'
  get '/users/:user_id/passengers/new', to: 'passengers#new', as: 'new_passenger'
  get '/users/:user_id/passengers/:id', to: 'passengers#show', as: 'passenger'
  get '/users/:user_id/passengers/:id/edit', to: 'passengers#edit', as: 'edit_passenger'

  
  
  
end

app/models/pilot.rb
class Pilot < ActiveRecord::Base
    belongs_to :user, optional: true
    has_many :flights
    has_many :destinations, through: :flights
    
    validates_presence_of :name, :rank
    validates :name, uniqueness: true
    scope :top_pilot, -> { order(flight_count: :desc).limit(1)}
   
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
    before_action :verified_user
    layout 'flightlayout' 
    
    def index
        @pilots = Pilot.all
        
        # if params[:search]
        #     @pilots = Pilot.search(params[:search])        
        # else
        #     @pilots = Pilot.all
        # end  
        
        
    end

    def most
        @pilots = Pilot.top_pilot
    end
    
    

    def show
        @pilot = Pilot.find(params[:id])
    end

    def new
        @pilot = Pilot.new
    end

    def create
        @pilot = Pilot.create(pilot_params)
        if @pilot.save
      
            redirect_to pilot_path(current_user,@pilot.id)
        else
            flash.now[:danger] = 'Pilot Info needs to be filled to continue'
            render :new
        
        end
    end

    def search
        if params[:search].blank?
            # flash.now[:danger] = 'Empty field!'
            redirect_to(pilots_path current_user, alert: "Empty field!")
            
        else
            @parameter = params[:search].downcase
            @results = Pilot.all.where("lower(name) LIKE :search ", search: @parameter )
        end
    end

   

    

    def edit
        @pilot = Pilot.find(params[:id])
    end

    def update
        @pilot = Pilot.find(params[:id])
        if @pilot.update_attributes(pilot_params)
            flash[:success] = "Destination updated"
            redirect_to @pilot
        else
            render 'edit'
        end   
    end

    def destroy
        @pilot = Pilot.find(params[:id])
        @pilot.destroy
        redirect_to pilots_path
    end
    private

    def pilot_params
        params.permit(:id, :name, :rank, :user_id, :search)
    end
    
end

app/views/pilots/_form.html.erb
  <div>
  <label>Rank:</label>
  <%= text_field_tag :rank, @pilot.rank  %><br>
  </div>
  <div>
  <label>Name</label>
  <%= text_field_tag :name, @pilot.name %><br>
  </div>
  <%= submit_tag "Submit" %>

app/views/pilots/edit.html.erb
<h2>Update Pilot</h2>

<div>
<%= form_tag @pilot, method: "put" do |f|%>
  <%= render 'form' %>
<% end %>
</div>


<%= link_to 'Back', user_pilots_path %>

app/views/pilots/index.html.erb
<header>
<div class='back_link'>
<p><%= link_to 'Back', user_path(current_user) %></p>
</div>


<div class= 'search'>
<%= form_tag(search_pilot_path, :method => "get") do %>
    <%= search_field_tag(:search, params[:search], placeholder: "Search for pilot") %>
    <%= submit_tag 'Search', name: nil %>
<% end %>
</div>
</header>
<div class='container'>

<div>
<% flash.each do |type, msg| %>
  <div>
    <li style="color:red;"><%= msg %></li>
  </div>

<% end %>
</div>




<h1>Current Pilot Roster</h1>
<h2><%= link_to 'Add a Pilot', new_pilot_path  %></h2>

<div>
<ul>
<% @pilots.each do |pilot|%>
   
    <% if current_user.admin %>
        <h4><li><%= pilot.rank %>, <%= pilot.name %> | <%= link_to 'Edit', edit_pilot_path(current_user, pilot) %> |  <%= link_to 'Delete',user_pilot_path(current_user, pilot), method: :delete %></li></h4>
           
    <% else %>
        <h4><li><%= pilot.rank %>, <%= pilot.name %></li></h4>
           
    <% end %>
<% end %>
</ul>
</div>

<div class='back_link'>
<p><%= link_to 'Back', user_path(current_user) %></p>
</div>
</div>

app/views/pilots/most.html.erb
<h2>Pilot with the most flights</h2>
<div class= 'container top_pilot'>
<ul>
<% @pilots.each do |pilot|%>
    <h3><li><%= pilot.name %> | <%= pilot.flight_count %></li></h3>
<% end %>
</ul>
</div>

<%= link_to 'Back', user_path(current_user) %>

app/views/pilots/new.html.erb
<div class ='container'>
<h2>Add a Pilot</h2>

<ul>
<% flash.each do |type, msg| %>
  <div>
    <li style="color:red;"><%= msg %></li>
  </div>

<% end %>
</ul>


<div>
<%= form_tag @pilot do |f|%>
  <%= render 'form' %>
<% end %>
</div>

<%= link_to 'Back', user_pilots_path %>

</div>

app/views/pilots/search.html.erb
<div class='container pilot'>
<h3>Pilot Search Results</h3>  

    <ul>
    <% @results.each do |result| %>  
        <h4><li><%= result.rank%> <%= link_to result.name, pilot_path(current_user, result) %></li><br></h4>  
    <% end %>
    </ul>


    <%= link_to 'Back', user_pilots_path %>
</div>

app/views/pilots/show.html.erb
<div class='container pilot'>
<h3>Added Pilot</h3>
<div>
    <p class='pilot_para'>Name: <%= @pilot.name %><br>Rank: <%= @pilot.rank %></p>
</div>

<%= link_to 'Back', user_pilots_path %>
</div>