config/routes.rb
Rails.application.routes.draw do
  
 
      resources :users, except:[:new, :show] do
      resources :destinations
      resources :flights, only: [:update, :destroy, :create]
      resources :pilots,  only: [:update, :destroy, :create]
      resources :passengers, only: [:update, :destroy, :create]
      
  

  end

      root to:'static#home'
     
      get '/auth/:provider/callback', :to => 'sessions#github_create'
      
  
 
  
      get '/users/signup', to: 'users#new', as: 'new_user'
      get '/login',  to: 'sessions#new', as: 'login'
      post 'login', to: 'sessions#create'
      get '/users/:id', to: 'users#show'
      delete '/users', to: 'users#destroy'
  
      delete 'session', to: 'sessions#destroy', as: 'logout'

      get '/users/:user_id/destinations', to: "destinations#index", as: 'destinations'
      get '/users/:user_id/destinations/:id', to: "destinations#show", as: 'destination'
  
 
      
      get '/users/:user_id/pilots/search' => 'pilots#search', :as => 'search_pilot'
 
  
  # post '/login'   to: 'sessions#create'
  # post '/signin', to: 'sessions#create'
 
  
  
  
 
  #destinations
  
  #users
  
  
  

  #flights
  get '/users/:user_id/flights', to: 'flights#index', as: 'flights'
  get '/users/:user_id/flights/new', to: 'flights#new', as: 'new_flight'
  get '/users/:user_id/flights/:id', to: 'flights#show', as: 'flight'
  get '/users/:user_id/flights/:id/edit', to: 'flights#edit', as: 'edit_flight'
  get '/users/:user_id/most', to: 'pilots#most', as: 'most_pilot'
  #pilot
  get '/users/:user_id/pilots', to: 'pilots#index', as: 'pilots'
  get '/users/:user_id/pilots/new', to: 'pilots#new', as: 'new_pilot'
  get '/users/:user_id/pilots/:id', to: 'pilots#show', as: 'pilot'
  get '/users/:user_id/pilots/:id/edit', to: 'pilots#edit', as: 'edit_pilot'
  
  
  #passenger
  get '/users/:user_id/pasengers', to: 'passengers#index', as: 'passengers'
  get '/users/:user_id/passengers/new', to: 'passengers#new', as: 'new_passenger'
  get '/users/:user_id/passengers/:id', to: 'passengers#show', as: 'passenger'
  get '/users/:user_id/passengers/:id/edit', to: 'passengers#edit', as: 'edit_passenger'

  
  
  
end

app/models/destination.rb
class Destination < ActiveRecord::Base
    has_many :flights
    has_many :pilots, through: :flights
    belongs_to :user , optional: true

    scope :order_by_name, -> { order(name: :asc) }
    

    
    
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :verified_user
    layout 'flightlayout'

    def index
        @destinations = Destination.order_by_name
    end

    def show
        @destination = Destination.find_by(id: params[:id])
    end

    def new
        @destination = Destination.new
    end

    def create
        @destination = Destination.new(dest_params)
        
            if @destination.save!
      # this route really does not need to be nested.
      # see https://guides.rubyonrails.org/routing.html#shallow-nesting
            redirect_to user_destination_path(current_user,@destination.id)
        else
      # re-render the form with errors
        render :new 
        end
        
    end

    

    def edit
        @destination = Destination.find(params[:id])
    end

    def update
        @destination = Destination.find(params[:id])
        if @destination.update_attributes(dest_params)
            flash[:success] = "Destination updated"
            redirect_to @destination
        else
            render 'edit'
        end   
    end

    def destroy
        @destination = Destination.find(params[:id])
        @destination.destroy
        redirect_to user_destinations_path
    end

    private

    def dest_params
        params.permit(:name)
    end

    
        
end

app/views/destinations/_form.html.erb
  <div>
  <label>Name</label>
  <%= text_field_tag :name, @destination.name %><br>
  </div>
  <%= submit_tag "Submit" %>

app/views/destinations/edit.html.erb
<div class="container text-center">
<h2>Update Destination</h2>

<div>
<div>
<%= form_tag @destination, method: "put" do |f|%>
  <%= render 'form' %>
<% end %>
</div>
</div>
</div>

app/views/destinations/index.html.erb
<div class ="container-fixed">
    <div class='options'>
    <p>Authorized Desitinations</p>
    <p><%= link_to 'Back', user_path(current_user) %></p>
    <p><%= link_to 'Add a destination', new_user_destination_path %></p>
    </div>
    <div class='content'>
    
    

     <div class='destinations'>
    <ul>
    <% @destinations.each do |destination|%>
        <% if current_user.admin %>
            <h3><li><%= link_to destination.name, user_destination_path(current_user, destination) %> (<%= destination.flights.count%>) | <%= link_to 'Edit', edit_user_destination_path(current_user, destination) %> | <%= link_to 'Delete',user_destination_path(current_user, destination), method: :delete %></li></h3> 
        <% else %>
            <h3><li><%= link_to destination.name, user_destination_path(current_user, destination) %> (<%= destination.flights.count %>) </li></h3>
        <% end %>
    <% end %>
    </ul>
    </div>
    
    
    </div>
    <div class='options'>
    <p><%= link_to 'Back', user_path(current_user) %></p>
    </div>
</div>

app/views/destinations/new.html.erb
<div class="container text-center">
<h2>Add a destination</h2>

<div>
<%= form_tag @destination do |f|%>
  <%= render 'form' %>
<% end %>
</div>
</div>

app/views/destinations/show.html.erb
<div class='container destshow'>
<div>
<h2>Destination</h2>
<div>
    <h3><%= @destination.name %></h3>
</div>
<div>
Current flights to this destination:
<ul>
<% @destination.flights.each do |flt| %>
<% if current_user.admin%>
<li>Flight Num: <%= link_to flt.flight_number, flight_path(current_user, flt) %> | <%= link_to 'Edit', edit_flight_path(current_user, flt) %> |  <%= link_to 'Delete',flight_path(current_user, flt), method: :delete %></li>
<% else %>
<li>Flight Num: <%= link_to flt.flight_number, flight_path(current_user, flt) %></li>
<% end %>
<% end %>
</ul>
</div>
</div>
<div class='back_link'>
<p><%= link_to 'Back', user_destinations_path %></p>
</div>
</div>